# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.4.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.4.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/phurley/code/projects/roboconfig

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/phurley/code/projects/roboconfig

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/phurley/code/projects/roboconfig/CMakeFiles /Users/phurley/code/projects/roboconfig/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/phurley/code/projects/roboconfig/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named roboconfig

# Build rule for target.
roboconfig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 roboconfig
.PHONY : roboconfig

# fast build rule for target.
roboconfig/fast:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/build
.PHONY : roboconfig/fast

src/config.o: src/config.cpp.o

.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/jsoncpp.o: src/jsoncpp.cpp.o

.PHONY : src/jsoncpp.o

# target to build an object file
src/jsoncpp.cpp.o:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/jsoncpp.cpp.o
.PHONY : src/jsoncpp.cpp.o

src/jsoncpp.i: src/jsoncpp.cpp.i

.PHONY : src/jsoncpp.i

# target to preprocess a source file
src/jsoncpp.cpp.i:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/jsoncpp.cpp.i
.PHONY : src/jsoncpp.cpp.i

src/jsoncpp.s: src/jsoncpp.cpp.s

.PHONY : src/jsoncpp.s

# target to generate assembly for a file
src/jsoncpp.cpp.s:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/jsoncpp.cpp.s
.PHONY : src/jsoncpp.cpp.s

src/mongoose.o: src/mongoose.cpp.o

.PHONY : src/mongoose.o

# target to build an object file
src/mongoose.cpp.o:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/mongoose.cpp.o
.PHONY : src/mongoose.cpp.o

src/mongoose.i: src/mongoose.cpp.i

.PHONY : src/mongoose.i

# target to preprocess a source file
src/mongoose.cpp.i:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/mongoose.cpp.i
.PHONY : src/mongoose.cpp.i

src/mongoose.s: src/mongoose.cpp.s

.PHONY : src/mongoose.s

# target to generate assembly for a file
src/mongoose.cpp.s:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/mongoose.cpp.s
.PHONY : src/mongoose.cpp.s

src/roboconfig.o: src/roboconfig.cpp.o

.PHONY : src/roboconfig.o

# target to build an object file
src/roboconfig.cpp.o:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/roboconfig.cpp.o
.PHONY : src/roboconfig.cpp.o

src/roboconfig.i: src/roboconfig.cpp.i

.PHONY : src/roboconfig.i

# target to preprocess a source file
src/roboconfig.cpp.i:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/roboconfig.cpp.i
.PHONY : src/roboconfig.cpp.i

src/roboconfig.s: src/roboconfig.cpp.s

.PHONY : src/roboconfig.s

# target to generate assembly for a file
src/roboconfig.cpp.s:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/roboconfig.cpp.s
.PHONY : src/roboconfig.cpp.s

src/server.o: src/server.cpp.o

.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i

.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s

.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

src/ws_file_tail.o: src/ws_file_tail.cpp.o

.PHONY : src/ws_file_tail.o

# target to build an object file
src/ws_file_tail.cpp.o:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/ws_file_tail.cpp.o
.PHONY : src/ws_file_tail.cpp.o

src/ws_file_tail.i: src/ws_file_tail.cpp.i

.PHONY : src/ws_file_tail.i

# target to preprocess a source file
src/ws_file_tail.cpp.i:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/ws_file_tail.cpp.i
.PHONY : src/ws_file_tail.cpp.i

src/ws_file_tail.s: src/ws_file_tail.cpp.s

.PHONY : src/ws_file_tail.s

# target to generate assembly for a file
src/ws_file_tail.cpp.s:
	$(MAKE) -f CMakeFiles/roboconfig.dir/build.make CMakeFiles/roboconfig.dir/src/ws_file_tail.cpp.s
.PHONY : src/ws_file_tail.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... roboconfig"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/jsoncpp.o"
	@echo "... src/jsoncpp.i"
	@echo "... src/jsoncpp.s"
	@echo "... src/mongoose.o"
	@echo "... src/mongoose.i"
	@echo "... src/mongoose.s"
	@echo "... src/roboconfig.o"
	@echo "... src/roboconfig.i"
	@echo "... src/roboconfig.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/ws_file_tail.o"
	@echo "... src/ws_file_tail.i"
	@echo "... src/ws_file_tail.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

